### ISSUE TITLE
Trouble Saving Notebooks To S3

### ISSUE THREAD

**Issue by jamesmcclain** [danielfrg/s3contents#21]
Hello, thank you for your project.

I am attempting to install and use your project within [this docker container](https://github.com/geodocker/geodocker-jupyter-geopyspark).  I am able to login with the code apparently active, but I am unable to see, upload, or download any data.  The steps that I am following are the following:

- I type `docker run -it --rm -p 8000:8000 --name geopyspark quay.io/geodocker/jupyter-geopyspark:6e5bbcc bash` to start the container
- Inside the container, I type `pip3 install --user s3contents` (or `pip3 install --user 'https://github.com/danielfrg/s3contents/archive/master.zip'`) to install the extension
- I create a file called `~/.jupyter/jupyter_notebook_config.py` with contents identical to the first example in the README, except with the access key, secret key, bucket name, and prefix appropriately set.
- I then run jupyterhub by typing `jupyterhub --no-ssl --Spawner.notebook_dir=/ -f ~/.jupyter/jupyter_notebook_config.py` or some variation thereof (chaning the spawner notebook, &c).
- I then proceed to `http://localhost:8000` and login with the username and password `hadoop` and `hadoop` as is normal for this container. 

The behavior that I am observing is:
- No files are listed after I login (that is, the directory within the bucket is not listed)
- Attempting to upload a notebook hangs and no notebook appears in my s3 bucket
- There is a constant network usage of between 500 kB/s and 1 mB/s going both up and down (even when pointing to an empty directory in the bucket).
- The network traffic seems to be coming from the following process `/usr/bin/python3.4 /usr/bin/jupyterhub-singleuser --user="hadoop" --cookie-name="jupyter-hub-token-hadoop" --base-url="/user/hadoop" --hub-host="" --hub-prefix="/hub/" --hub-` (sorry, that seems to be cut-off but it is all that I could get due to an apparent problem with the way docker interacts with my terminal)

Thank you.

**Comment by jpolchlo** [comment]
I see that you closed this issue, but I was having the same problem and figured out the solution.  For the sake of posterity, I want to present the solution here.

The problem you encountered has to do with the use of JupyterHub.  The configuration provided to JupyterHub via the `-f` flag affects the hub instance.  You need to specify the use of S3Contents in a separate, per-user configuration in each users' `$HOME/.jupyter/jupyter_notebook_config.py` if you want the single user notebook servers to have those configurations.  This makes sense when you consider that each user would want to select a different access key/secret key/bucket/prefix combination rather than rely on some global default.

Hope this helps.

**Comment by jamesmcclain** [comment]
:+1:
