### ISSUE TITLE
How to use saved files from the notebook?

### ISSUE THREAD

**Issue by gcavalcante8808** [danielfrg/s3contents#46]
Hi Folks,

I have a notebook that reads a file from current dir and the jupyter is already configured to use s3contents. In my case, I can create and save file, but when I try to open the file, the python interpreter returns FileNotFound ...

Example (clusterSpec.json
```
with open('clusterSpec.json','r') as specfile:
    json.loads(specfile)
```
So ... I wonder ... How to read a file saved in the s3? Im using minio btw.

**Comment by danielfrg** [comment]
Thats not going to work because Python `open` is looking at the local filesystem.

You need to use boto or s3fs or another python library that allows you to read files directly s3.

This project uses s3fs but I want to move it to `fs-s3fs` (https://github.com/PyFilesystem/s3fs) that looks more stable.
