### ISSUE TITLE
New version in pypi - commit 550403f7de5a329d235fc2c81a2255e3407556ea

### ISSUE THREAD

**Issue by peter-friedland-bose** [danielfrg/s3contents#82]
Hi - I might be mistaken but I don't think the latest and greatest (commit 550403f7de5a329d235fc2c81a2255e3407556ea Adding a way do a custom boto3 instantiation to s3contents) has been uploaded to pypi.org. These are the from the pull request initiated by @milutz.  
I managed to install the latest from GitHub anyway and it all seems to work well.  
Thanks !!
Peter Friedland

**Comment by milutz** [comment]
@peter-friedland-bose 
I believe this is the expected behavior.

The PR was merged, but the release cycle (the point that Daniel pushes things to pypi) _isn't_ tied to merges.  The release cycle only happens when he has a number of things (or something big) that he fells needs a release.

My recommendation would be to click on the GitHub "watch" button for the project and set it for "releases" - then GitHub will let you know when he does a release of master (so won't have to clone any more).

**Comment by danielfrg** [comment]
Released 0.3.2 with that PR: https://pypi.org/project/s3contents/0.3.2/
Enjoy!
